version: "2"
services:
  cve-service-1:
    build:
      context: https://github.com/dweinand/cve-service-1.git
    volumes:
      - .:/cve
  cve-service-2:
    build:
      context: https://github.com/dweinand/cve-service-2.git
    volumes:
      - .:/cve
