version: "2"
services:
  cve-service-1:
    build:
      context: https://github.com/dweinand/cve-service-1.git
    volumes:
      - .:/cve
    environment:
      BUILDKITE_PARALLEL_JOB:
      BUILDKITE_PARALLEL_JOB_COUNT:
      BUILDKITE_COMMIT:
      BUILDKITE_BRANCH:
      BUILDKITE_REPO:
      BUILDKITE_BUILD_ID:
      BUILDKITE_BUILD_NUMBER:
  cve-service-2:
    build:
      context: https://github.com/dweinand/cve-service-2.git
    volumes:
      - .:/cve
    environment:
      BUILDKITE_PARALLEL_JOB:
      BUILDKITE_PARALLEL_JOB_COUNT:
      BUILDKITE_COMMIT:
      BUILDKITE_BRANCH:
      BUILDKITE_REPO:
      BUILDKITE_BUILD_ID:
      BUILDKITE_BUILD_NUMBER:
